model:
  base_learning_rate: 1.0e-5
  target: sgm.models.diffusers_autoencoder.DiffusersAutoencoderKLWanWrapper
  params:
    input_key: mp4
    monitor: "val/loss/rec"
    disc_start_iter: 50001
    pretrained_model_name_or_path: Wan-AI/Wan2.1-T2V-1.3B-Diffusers
    subfolder: vae
    trainable_ae_params:
      - ["decoder", "post_quant_conv"]

    lossconfig:
      target: sgm.modules.autoencoding.losses.GeneralLPIPSWithDiscriminator
      params:
        perceptual_weight: 0.25
        disc_start: 50001
        disc_weight: 0.5
        dims: 3
        learn_logvar: false

        regularization_weights:
          kl_loss: 1.0e-6

data:
  target: sgm.data.ucf101.UCF101Loader
  params:
    batch_size: 4
    num_workers: 4
    prefetch_factor: 2
    shuffle: true
    drop_last: true
    pin_memory: true

    train:
      root_dir: /path/to/UCF101
      frames_per_clip: 17
      step_between_clips: 17
      transform_config:
        image_transforms:
          - target: torchvision.transforms.v2.Resize
            params:
              size: 128
              antialias: true
          - target: torchvision.transforms.v2.RandomCrop
            params:
              size: 128
          - target: torchvision.transforms.v2.RandomHorizontalFlip
            params:
              p: 0.5

    test:
      root_dir: /path/to/UCF101
      frames_per_clip: 17
      step_between_clips: 17
      transform_config:
        size: 128

lightning:
  strategy:
    target: pytorch_lightning.strategies.DDPStrategy
    params:
      find_unused_parameters: True

  modelcheckpoint:
    params:
      every_n_epochs: 1

  callbacks:
    save_diffusers:
      target: sgm.callback.SaveDiffusersCallback
      params:
        save_dir: diffusers
        every_n_epochs: 1
        export_on_train_end: true
        safe_serialization: true

    video_logger:
      target: main.VideoLogger
      params:
        max_videos: 4
        fps: 8
        enable_autocast: false

  trainer:
    precision: 32-true
    devices: 0, 1, 2, 3
    limit_val_batches: 50
    benchmark: True
    accumulate_grad_batches: 1
    check_val_every_n_epoch: 1
    max_epochs: 100
