model:
  base_learning_rate: 5.0e-5
  target: sgm.models.autoencoder.AutoencoderKL
  params:
    input_key: jpg
    monitor: "val/loss/rec"
    disc_start_iter: 50001
    embed_dim: 4

    ddconfig:
      attn_type: none
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult: [1, 2, 2, 2]
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: sgm.modules.autoencoding.losses.DistillationLossWithDiscriminator
      params:
        pretrained_model_name_or_path: /aiarena/group/gmgroup/hongyq/models/stabilityai/sd-vae-ft-mse
        latent_weight: 1.0
        logvar_weight: 0.05
        pixel_loss: l1
        perceptual_weight: 0.25
        disc_start: 50001
        disc_weight: 1.0

data:
  target: sgm.data.imagenet.ImageNetLoader
  params:
    batch_size: 8
    num_workers: 4
    prefetch_factor: 2
    shuffle: true

    train:
      root_dir: /path/to/ImageNet
      size: 256
      transform: true
    validation:
      root_dir: /path/to/ImageNet
      size: 256
      transform: true

lightning:
  strategy:
    target: pytorch_lightning.strategies.DDPStrategy
    params:
      find_unused_parameters: True

  modelcheckpoint:
    params:
      every_n_epochs: 1

  callbacks:
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_train_steps: 50000

    image_logger:
      target: main.ImageLogger
      params:
        enable_autocast: False
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    precision: 32-true
    devices: 0, 1, 2, 3
    limit_val_batches: 50
    benchmark: True
    accumulate_grad_batches: 1
    check_val_every_n_epoch: 1
    max_epochs: 100
